
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website-deployment
  labels: 
    app: simpleweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: nginxdemos/hello
        imagePullPolicy: Always
        ports:
        - containerPort: 80